cd js
cd Server
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
node server.js
